-- Karaoke Room Management (React + Supabase)
-- Run this file in Supabase SQL Editor.

begin;

create table if not exists public.rooms (
  id bigint generated by default as identity primary key,
  name varchar(50) not null,
  price_per_hour integer not null default 120,
  created_at timestamptz not null default now(),
  constraint rooms_name_length check (char_length(trim(name)) between 3 and 50),
  constraint rooms_price_range check (price_per_hour between 1 and 10000)
);

create table if not exists public.sessions (
  id bigint generated by default as identity primary key,
  room_id bigint not null references public.rooms(id) on delete cascade,
  customer_name varchar(100) not null,
  start_time bigint not null,
  duration_seconds integer not null,
  status text not null default 'active',
  actual_end_time bigint,
  created_at timestamptz not null default now(),
  constraint sessions_customer_name_not_empty check (char_length(trim(customer_name)) > 0),
  constraint sessions_duration_range check (duration_seconds between 3600 and 28800),
  constraint sessions_status_valid check (status in ('active', 'ended'))
);

create unique index if not exists sessions_one_active_per_room
  on public.sessions (room_id)
  where status = 'active';

create index if not exists idx_sessions_room_status
  on public.sessions (room_id, status);

create index if not exists idx_sessions_created_at
  on public.sessions (created_at desc);

alter table public.rooms enable row level security;
alter table public.sessions enable row level security;

drop policy if exists rooms_select on public.rooms;
drop policy if exists rooms_insert on public.rooms;
drop policy if exists rooms_update on public.rooms;
drop policy if exists rooms_delete on public.rooms;

create policy rooms_select on public.rooms for select to anon, authenticated using (true);
create policy rooms_insert on public.rooms for insert to anon, authenticated with check (true);
create policy rooms_update on public.rooms for update to anon, authenticated using (true) with check (true);
create policy rooms_delete on public.rooms for delete to anon, authenticated using (true);

drop policy if exists sessions_select on public.sessions;
drop policy if exists sessions_insert on public.sessions;
drop policy if exists sessions_update on public.sessions;
drop policy if exists sessions_delete on public.sessions;

create policy sessions_select on public.sessions for select to anon, authenticated using (true);
create policy sessions_insert on public.sessions for insert to anon, authenticated with check (true);
create policy sessions_update on public.sessions for update to anon, authenticated using (true) with check (true);
create policy sessions_delete on public.sessions for delete to anon, authenticated using (true);

insert into public.rooms (name, price_per_hour)
select room_name, room_price
from (
  values
    ('Room 1', 120),
    ('Room 2', 120),
    ('Room 3', 120),
    ('Room 4', 120),
    ('Room 5', 120),
    ('Room 6', 120),
    ('Room 7', 120),
    ('Room 8', 120),
    ('Room 9', 120),
    ('Room 10', 120)
) as defaults(room_name, room_price)
where not exists (
  select 1 from public.rooms limit 1
);

create or replace function public.get_history_summary()
returns table (
  total_bookings bigint,
  active_bookings bigint,
  total_revenue numeric
)
language sql
security invoker
as $$
  select
    count(*) as total_bookings,
    count(*) filter (where s.status = 'active') as active_bookings,
    coalesce(sum((s.duration_seconds::numeric / 3600) * r.price_per_hour), 0) as total_revenue
  from public.sessions s
  join public.rooms r on r.id = s.room_id;
$$;

grant execute on function public.get_history_summary() to anon, authenticated;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'rooms'
    ) then
      execute 'alter publication supabase_realtime add table public.rooms';
    end if;

    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'sessions'
    ) then
      execute 'alter publication supabase_realtime add table public.sessions';
    end if;
  end if;
end;
$$;

commit;